### PR TITLE
Add new component slot syntax [Alternative]

### PR DESCRIPTION
**Pull request by Jubeki**
Alternative to: https://github.com/ryangjchandler/prettier-plugin-blade/pull/33

This is my preferred approach.

### CODE REVIEW

**Comment by Jubeki** [comment]
Be aware that the new syntax is only available since Laravel 9.

**Comment by Jubeki** [comment]
Maybe the replacement can be hidden behind a option flag.
I prefer the new syntax over the old one, but the formatter could be used with older Laravel versions.

**Comment by ryangjchandler** [comment]
@Jubeki Going to close this one too. I don't think we're at the point yet where it warrants having this kind of formatting option. Laravel 9 has only just been released.

**Comment by Jubeki** [comment]
Okay 👍

**Pull request closed without merging**
